language: node_js
node_js:
  - '5.4'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: gulp clientTest
notifications:
  email: false
services:
  - postgresql
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
    - CXX=g++-4.8
    - TRAVIS_SECURE_ENV_VARS=true
    - secure: "GtupdldIHzfy6b3jGb7fYfLqcuhbL9d8ifX/zZpNBJ5R3LnDrJBOkuFox4deeypq3wUlp4nzKSaLe/EYf//wccA+N2AwXEEc5INdFDD1qvBYQr9MheHh/HXnWj88YlvD4ZHqtA1Wp0efFWOTzghqVUJVzBfmt+9isQlsdl711fxq9GmVvZieB8QQtqk3ri82po+3OZihXcFCPdly2VPPJeltpbxLayLdEh6WgYlSGJ6H/wTXqSbLJZYtYH5WJTg0M/h6zP717A/58sP6CSwiJaWc/sOycwOfNEP5W2uIE9fLIRGSdKEMq3Tritifr8vGB1ZgiXoD9bCZrplEkdL7G7wD72q0G2vPaliGjGnLMgiO9IAfOep5FwC3F/qOtcGo2HHG9Q8PAiI/+deGwG3M95dmlXT2OiOQrbhKsAgC8lEL5XJ7FSVpcC/GVV9Au0L1BZ4f56N5hqu83OBfEQMRcC5OTTocXjdUCgTg1LmZWKBcuen0SALS4IdDCl1EYyB+FV2/cba4iUQAm9qUIPyjxbfb+gBEFdAP9oxojmpOCMRvdnVBMhWvpe+Up4h4KQq8P3yXa4hF1EAEQ13A3dYJGeoA2y6M4xUWGpzjnEimc1IWNF/LyVCnqRMzi+A3ONNmIuGiiXAX8fAeYMAwJnXMePYZ6UDFPavmvjc6D6pTyI4="
