language: node_js
node_js:
  - '4'
before_install:
  - npm install -g npm
before_script:
  # - 'export CHROME_BIN=chromium-browser'
  # - npm install
  - npm install -g gulp
script: gulp test:server
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
#   slack: mks31:v3TzTDrOf5TAzxkyflH1uzr9
