language: node_js
node_js:
  - '0.1'
before_install:
  # - npm install -g npm
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g gulp
script: gulp clientTest
# node_modules/karma/bin/karma start karma.config.js --single-run
notifications:
  email: false
sudo: false
cache:
  directories:
    - node_modules
# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - g++-4.8
# env:
#   CXX=g++-4.8
